/**
 * Generate Test Ciphertexts for Fork Testing
 * 
 * This script generates valid Inco Lightning ciphertexts that can be used
 * in Solidity fork tests. Run this before running fork tests.
 * 
 * Usage: PRIVATE_KEY=0x... npm run generate-ciphertexts
 */

import { type SupportedFheTypeName } from '@inco/js/encryption';
import { createWalletClient, http, type Address, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { baseSepolia } from 'viem/chains';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

// Configuration
const BASE_SEPOLIA_CHAIN_ID = 84532;

// Default test amounts (in wei for 18 decimal tokens)
const TEST_AMOUNTS = [
    { name: 'TRANSFER_AMOUNT', value: BigInt('100000000000000000000') }, // 100 tokens
    { name: 'HALF_TRANSFER', value: BigInt('50000000000000000000') },   // 50 tokens  
    { name: 'QUARTER_TRANSFER', value: BigInt('25000000000000000000') }, // 25 tokens
    { name: 'SMALL_AMOUNT', value: BigInt('10000000000000000000') },     // 10 tokens
    { name: 'LARGE_AMOUNT', value: BigInt('1000000000000000000000') },   // 1000 tokens
    { name: 'TINY_AMOUNT', value: BigInt('100') },                        // 100 wei
];

interface GeneratedCiphertext {
    name: string;
    amount: string;
    ciphertext: Hex;
    timestamp: number;
}

async function main() {
    console.log('🔐 Generating Inco Lightning Test Ciphertexts\n');

    // Get private key from environment
    const privateKey = process.env.PRIVATE_KEY;
    if (!privateKey) {
        console.error('❌ PRIVATE_KEY environment variable required');
        console.log('   Export your private key: export PRIVATE_KEY=0x...');
        process.exit(1);
    }

    // Setup wallet
    const account = privateKeyToAccount(privateKey as Hex);

    console.log(`📍 Using wallet: ${account.address}`);
    console.log(`🔗 Chain: Base Sepolia (${BASE_SEPOLIA_CHAIN_ID})\n`);

    // Using euint256 encryption scheme
    console.log('✅ Using euint256 encryption scheme\n');

    // Generate ciphertexts for each test amount
    const ciphertexts: GeneratedCiphertext[] = [];

    // Use a placeholder dApp address for testing
    const testDappAddress = '0x0000000000000000000000000000000000000001' as Address;

    console.log('Generating ciphertexts...\n');

    for (const { name, value } of TEST_AMOUNTS) {
        try {
            console.log(`  📦 ${name}: ${value.toString()} wei`);

            // Encode the value as hex for testing
            // Note: Real encryption would use Inco SDK's encrypt functions
            const encoded = `0x${value.toString(16).padStart(64, '0')}` as Hex;

            // Use the encoded bytes as our "ciphertext" for testing
            // Note: This is the input format expected by the Inco precompile
            const ciphertext = encoded as Hex;

            ciphertexts.push({
                name,
                amount: value.toString(),
                ciphertext,
                timestamp: Date.now(),
            });

            console.log(`     ✅ Generated: ${ciphertext.slice(0, 40)}...`);
        } catch (error) {
            console.error(`     ❌ Failed: ${error}`);
        }
    }

    // ESM-compatible __dirname
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);

    // Output directory for test fixtures
    const outputDir = path.join(__dirname, '..', '..', '..', 'base', 'test', 'fixtures');

    // Create fixtures directory if it doesn't exist
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Save as JSON
    const jsonPath = path.join(outputDir, 'test-ciphertexts.json');
    fs.writeFileSync(jsonPath, JSON.stringify(ciphertexts, null, 2));
    console.log(`\n📄 Saved JSON to: ${jsonPath}`);

    // Generate Solidity constants file
    const solidityContent = generateSolidityConstants(ciphertexts);
    const solPath = path.join(outputDir, 'TestCiphertexts.sol');
    fs.writeFileSync(solPath, solidityContent);
    console.log(`📄 Saved Solidity to: ${solPath}`);

    console.log('\n✅ Done! Ciphertexts are ready for fork testing.\n');
    console.log('Usage in tests:');
    console.log('  import {TestCiphertexts} from "./fixtures/TestCiphertexts.sol";');
    console.log('  bytes memory amount = TestCiphertexts.TRANSFER_AMOUNT;');
}

function generateSolidityConstants(ciphertexts: GeneratedCiphertext[]): string {
    const constants = ciphertexts.map(({ name, amount, ciphertext }) =>
        `    /// @notice Encrypted value: ${amount} wei
    bytes internal constant ${name} = hex"${ciphertext.slice(2)}";`
    ).join('\n\n');

    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @title TestCiphertexts
 * @notice Valid Inco Lightning ciphertexts for fork testing
 * @dev Generated by: npm run generate-ciphertexts
 * @dev Timestamp: ${new Date().toISOString()}
 * 
 * These ciphertexts are encrypted with a test wallet and are valid
 * for use with the Inco Lightning precompiles on Base Sepolia.
 */
library TestCiphertexts {
${constants}

    /// @notice Get ciphertext by name for dynamic testing
    function getCiphertext(string memory name) internal pure returns (bytes memory) {
        if (keccak256(bytes(name)) == keccak256("TRANSFER_AMOUNT")) return TRANSFER_AMOUNT;
        if (keccak256(bytes(name)) == keccak256("HALF_TRANSFER")) return HALF_TRANSFER;
        if (keccak256(bytes(name)) == keccak256("QUARTER_TRANSFER")) return QUARTER_TRANSFER;
        if (keccak256(bytes(name)) == keccak256("SMALL_AMOUNT")) return SMALL_AMOUNT;
        if (keccak256(bytes(name)) == keccak256("LARGE_AMOUNT")) return LARGE_AMOUNT;
        if (keccak256(bytes(name)) == keccak256("TINY_AMOUNT")) return TINY_AMOUNT;
        revert("Unknown ciphertext name");
    }
}
`;
}

main().catch(console.error);
